package config

const (
	envStrAPIListenerPort   = "API_LISTENER"
	envStrAPIVersion        = "API_VERSION"
	envStrAPIUIURL          = "API_UI_URL"
	envStrAPIJWTSecret      = "API_JWT_SECRET"
	envStrHTTPListenerPort  = "HTTP_LISTENER"
	envStrHTTPSListenerPort = "HTTPS_LISTENER"
	envStrLetsEncryptURL    = "LETSENCRYPT_URL"
	envStrUsePebble         = "USE_PEBBLE"
	envStrPebbleCAURL       = "PEBBLE_CA_URL"
	envStrUseStage          = "USE_STAGE"
	envStrLogLevel          = "LOG_LEVEL"
	envStrLogFormatter      = "LOG_FORMATTER"
	envStrBootstrap         = "BOOTSTRAP"
	envStrCacheInterval     = "CACHE_INTERVAL"
	envStrTableNamePrefix   = "TABLE_PREFIX"
	envStrDBRegion          = "DB_REGION"
	envStrTableRedirects    = "TABLE_REDIRECTS"
	envStrTableCertCache    = "TABLE_CERTCACHE"
	envStrTableUsers        = "TABLE_USERS"
	envStrDBKey             = "DB_KEY"
	envStrDBSecret          = "DB_SECRET"
	envStrDBEndpoint        = "DB_ENDPOINT"
)
